<?php
require "vendor/autoload.php";

use GetOptionKit\OptionCollection;
use GetOptionKit\OptionParser;
use GetOptionKit\OptionPrinter\ConsoleOptionPrinter;

$specs = new OptionCollection;
$specs->add('f|file:', 'file includes captions line by line' )
    ->isa('File');
$specs->add('d|duration:', 'duration of sequence')
    ->isa('Number');
$specs->add('n|name?', 'name of the sequence')
    ->isa('String')
    ->defaultValue('captions');
$specs->add('t|template?', 'template file name')
    ->isa('String')
    ->defaultValue('template.xml');
$specs->add('ct|caption-template?', 'caption template file name')
    ->isa('String')
    ->defaultValue('caption_template.txt');
$specs->add('o|output?', 'output file name')
    ->isa('String')
    ->defaultValue('output.xml');

$parser = new OptionParser($specs);

$str = "Zg8AAAAAAAB7ACIAbQBTAGgAYQBkAG8AdwBGAG8AbgB0AE0AYQBwAEgAYQBzAGgAIgA6ACIAZgBhADcANQAwADIAOQA5AC0AZAA2ADgAYQAtADIAZQBkADAALQBlADAAYgA2AC0AZgA3ADIAMwAwADAAMAAwADAAMABjADUAIgAsACIAbQBUAGUAeAB0AFAAYQByAGEAbQAiADoAewAiAG0AQQBsAGkAZwBuAG0AZQBuAHQAIgA6ADIALAAiAG0AQgBhAGMAawBGAGkAbABsAEMAbwBsAG8AcgAiADoANgA3ADEAMAA2ADIAOQAsACIAbQBCAGEAYwBrAEYAaQBsAGwATwBwAGEAYwBpAHQAeQAiADoAMgA3AC4AMwAxADkANQA4ADUAOAAwADAAMQA3ADAAOAA5ADgALAAiAG0AQgBhAGMAawBGAGkAbABsAFMAaQB6AGUAIgA6ADUAMAAsACIAbQBCAGEAYwBrAEYAaQBsAGwAVgBpAHMAaQBiAGwAZQAiADoAZgBhAGwAcwBlACwAIgBtAEQAZQBmAGEAdQBsAHQAUgB1AG4AIgA6AFsAXQAsACIAbQBIAGUAaQBnAGgAdAAiADoAMAAsACIAbQBIAGkAbgBkAGkARABpAGcAaQB0AHMAIgA6AGYAYQBsAHMAZQAsACIAbQBJAG4AZABpAGMAIgA6AGYAYQBsAHMAZQAsACIAbQBJAHMATQBhAHMAawAiADoAZgBhAGwAcwBlACwAIgBtAEkAcwBNAGEAcwBrAEkAbgB2AGUAcgB0AGUAZAAiADoAZgBhAGwAcwBlACwAIgBtAEkAcwBWAGUAcgB0AGkAYwBhAGwAVABlAHgAdAAiADoAZgBhAGwAcwBlACwAIgBtAEwAZQBhAGQAaQBuAGcAIgA6ADQALAAiAG0ATABpAGcAYQB0AHUAcgBlAHMAIgA6AGYAYQBsAHMAZQAsACIAbQBMAGkAbgBlAEMAYQBwAFQAeQBwAGUAIgA6ADAALAAiAG0ATABpAG4AZQBKAG8AaQBuAFQAeQBwAGUAIgA6ADAALAAiAG0ATQBpAHQAZQByAEwAaQBtAGkAdAAiADoAMgAuADUALAAiAG0ATgB1AG0AUwB0AHIAbwBrAGUAcwAiADoAMQAsACIAbQBSAFQATAAiADoAZgBhAGwAcwBlACwAIgBtAFMAaABhAGQAbwB3AEEAbgBnAGwAZQAiADoAMQAzADUALAAiAG0AUwBoAGEAZABvAHcAQgBsAHUAcgAiADoAMgA1ADAALAAiAG0AUwBoAGEAZABvAHcAQwBvAGwAbwByACIAOgAwACwAIgBtAFMAaABhAGQAbwB3AE8AZgBmAHMAZQB0ACIAOgAxADAALAAiAG0AUwBoAGEAZABvAHcATwBwAGEAYwBpAHQAeQAiADoAMQAwADAALAAiAG0AUwBoAGEAZABvAHcAUwBpAHoAZQAiADoAMAAsACIAbQBTAGgAYQBkAG8AdwBWAGkAcwBpAGIAbABlACIAOgB0AHIAdQBlACwAIgBtAFMAdAB5AGwAZQBTAGgAZQBlAHQAIgA6AHsAIgBtAEEAZABkAGkAdABpAG8AbgBhAGwAUwB0AHIAbwBrAGUAQwBvAGwAbwByACIAOgBbAF0ALAAiAG0AQQBkAGQAaQB0AGkAbwBuAGEAbABTAHQAcgBvAGsAZQBWAGkAcwBpAGIAbABlACIAOgBbAF0ALAAiAG0AQQBkAGQAaQB0AGkAbwBuAGEAbABTAHQAcgBvAGsAZQBXAGkAZAB0AGgAIgA6AFsAXQAsACIAbQBCAGEAcwBlAGwAaQBuAGUATwBwAHQAaQBvAG4AIgA6AHsAIgBtAFAAYQByAGEAbQBWAGEAbAB1AGUAcwAiADoAWwBbADAALAAwAF0AXQB9ACwAIgBtAEIAYQBzAGUAbABpAG4AZQBTAGgAaQBmAHQAIgA6AHsAIgBtAFAAYQByAGEAbQBWAGEAbAB1AGUAcwAiADoAWwBbADAALAAwAF0AXQB9ACwAIgBtAEMAYQBwAHMATwBwAHQAaQBvAG4AIgA6AHsAIgBtAFAAYQByAGEAbQBWAGEAbAB1AGUAcwAiADoAWwBbADAALAAwAF0AXQB9ACwAIgBtAEYAYQB1AHgAQgBvAGwAZAAiADoAewAiAG0AUABhAHIAYQBtAFYAYQBsAHUAZQBzACIAOgBbAFsAMAAsAGYAYQBsAHMAZQBdAF0AfQAsACIAbQBGAGEAdQB4AEkAdABhAGwAaQBjACIAOgB7ACIAbQBQAGEAcgBhAG0AVgBhAGwAdQBlAHMAIgA6AFsAWwAwACwAZgBhAGwAcwBlAF0AXQB9ACwAIgBtAEYAaQBsAGwAQwBvAGwAbwByACIAOgB7ACIAbQBQAGEAcgBhAG0AVgBhAGwAdQBlAHMAIgA6AFsAWwAwACwAMwAzADYAOQA3ADIANwBdACwAWwAxACwAMwAzADYAOQA3ADIANwBdACwAWwAyACwAMwAzADYAOQA3ADIANwBdACwAWwAzACwAMwAzADYAOQA3ADIANwBdACwAWwA0ACwAMwAzADYAOQA3ADIANwBdACwAWwA1ACwAMwAzADYAOQA3ADIANwBdACwAWwA2ACwAMwAzADYAOQA3ADIANwBdACwAWwA3ACwAMwAzADYAOQA3ADIANwBdACwAWwA4ACwAMwAzADYAOQA3ADIANwBdACwAWwA5ACwAMQA2ADcANwA3ADIAMQA1AF0AXQB9ACwAIgBtAEYAaQBsAGwATwB2AGUAcgBTAHQAcgBvAGsAZQAiADoAewAiAG0AUABhAHIAYQBtAFYAYQBsAHUAZQBzACIAOgBbAFsAMAAsAHQAcgB1AGUAXQBdAH0ALAAiAG0ARgBpAGwAbABWAGkAcwBpAGIAbABlACIAOgB7ACIAbQBQAGEAcgBhAG0AVgBhAGwAdQBlAHMAIgA6AFsAWwAwACwAdAByAHUAZQBdAF0AfQAsACIAbQBGAG8AbgB0AE4AYQBtAGUAIgA6AHsAIgBtAFAAYQByAGEAbQBWAGEAbAB1AGUAcwAiADoAWwBbADAALAAiAFkAdQBHAG8ALQBCAG8AbABkACIAXQAsAFsAMQAsACIAWQB1AEcAbwAtAEIAbwBsAGQAIgBdACwAWwAyACwAIgBZAHUARwBvAC0AQgBvAGwAZAAiAF0ALABbADMALAAiAFkAdQBHAG8ALQBCAG8AbABkACIAXQAsAFsANAAsACIAWQB1AEcAbwAtAEIAbwBsAGQAIgBdACwAWwA1ACwAIgBZAHUARwBvAC0AQgBvAGwAZAAiAF0ALABbADYALAAiAFkAdQBHAG8ALQBCAG8AbABkACIAXQAsAFsANwAsACIAWQB1AEcAbwAtAEIAbwBsAGQAIgBdACwAWwA4ACwAIgBZAHUARwBvAC0AQgBvAGwAZAAiAF0ALABbADkALAAiADUAOAA3ADIANAAyADAAMgAtAEQARAA1ADgALQA0ADIAMABCAC0AQQA2AEYAMAAtADIARgBCAEIAQwA4ADEAMgBGADcAQgA1ACIAXQBdAH0ALAAiAG0ARgBvAG4AdABTAGkAegBlACIAOgB7ACIAbQBQAGEAcgBhAG0AVgBhAGwAdQBlAHMAIgA6AFsAWwAwACwAOAA1AF0ALABbADEALAA4ADUAXQAsAFsAMgAsADgANQBdACwAWwAzACwAOAA1AF0ALABbADQALAA4ADUAXQAsAFsANQAsADgANQBdACwAWwA2ACwAOAA1AF0ALABbADcALAA4ADUAXQAsAFsAOAAsADgANQBdACwAWwA5ACwAMQAwADAAXQBdAH0ALAAiAG0ASwBlAHIAbgBpAG4AZwAiADoAewAiAG0AUABhAHIAYQBtAFYAYQBsAHUAZQBzACIAOgBbAFsAMAAsADAAXQBdAH0ALAAiAG0AUwB0AHIAbwBrAGUAQwBvAGwAbwByACIAOgB7ACIAbQBQAGEAcgBhAG0AVgBhAGwAdQBlAHMAIgA6AFsAWwAwACwAMQA2ADcANwA3ADIAMQA1AF0AXQB9ACwAIgBtAFMAdAByAG8AawBlAFYAaQBzAGkAYgBsAGUAIgA6AHsAIgBtAFAAYQByAGEAbQBWAGEAbAB1AGUAcwAiADoAWwBbADAALAB0AHIAdQBlAF0ALABbADEALAB0AHIAdQBlAF0ALABbADIALAB0AHIAdQBlAF0ALABbADMALAB0AHIAdQBlAF0ALABbADQALAB0AHIAdQBlAF0ALABbADUALAB0AHIAdQBlAF0ALABbADYALAB0AHIAdQBlAF0ALABbADcALAB0AHIAdQBlAF0ALABbADgALAB0AHIAdQBlAF0ALABbADkALABmAGEAbABzAGUAXQBdAH0ALAAiAG0AUwB0AHIAbwBrAGUAVwBpAGQAdABoACIAOgB7ACIAbQBQAGEAcgBhAG0AVgBhAGwAdQBlAHMAIgA6AFsAWwAwACwAOABdACwAWwAxACwAOABdACwAWwAyACwAOABdACwAWwAzACwAOABdACwAWwA0ACwAOABdACwAWwA1ACwAOABdACwAWwA2ACwAOABdACwAWwA3ACwAOABdACwAWwA4ACwAOABdACwAWwA5ACwAMQBdAF0AfQAsACIAbQBUAGUAeAB0ACIAOgAiAIZ2VTCTMAEwUzCTMGswYTBvMCIALAAiAG0AVAByAGEAYwBrAGkAbgBnACIAOgB7ACIAbQBQAGEAcgBhAG0AVgBhAGwAdQBlAHMAIgA6AFsAWwAwACwAMABdAF0AfQAsACIAbQBUAHMAdQBtAGkAIgA6AHsAIgBtAFAAYQByAGEAbQBWAGEAbAB1AGUAcwAiADoAWwBbADAALAAwAF0AXQB9ACwAIgBtAFUAbgBkAGUAcgBsAGkAbgBlACIAOgB7ACIAbQBQAGEAcgBhAG0AVgBhAGwAdQBlAHMAIgA6AFsAWwAwACwAZgBhAGwAcwBlAF0AXQB9AH0ALAAiAG0AVABhAGIAVwBpAGQAdABoACIAOgA0ADAAMAAsACIAbQBWAGUAcgB0AGkAYwBhAGwAQQBsAGkAZwBuAG0AZQBuAHQAIgA6ADIALAAiAG0AVwBpAGQAdABoACIAOgAwAH0ALAAiAG0AVQBzAGUATABlAGcAYQBjAHkAVABlAHgAdABCAG8AeAAiADoAZgBhAGwAcwBlACwAIgBtAFYAZQByAHMAaQBvAG4AIgA6ADEAfQA=";
$decoded = base64_decode($str);
$first = mb_substr($decoded, 0, 8);
try {
    $result = $parser->parse($argv);
    $captionTemplate = file_get_contents($result->captionTemplate);
    $template = new DOMDocument();
    $template->load($result->template);
    $xpath = new DOMXPath($template);
    $xpath->query('//sequence/name')->item(0)->nodeValue = $result->name;
    $captions = file($result->file);
    $interval = (int)($result->duration / count($captions));

    $track = $xpath->query('//sequence/media/video/track[2]')->item(0);
    foreach($captions as $index => $caption){
        if($index > 1){
            $clipitem = $xpath->query('//sequence/media/video/track[2]/clipitem[2]')->item(0)->cloneNode(true);
            $clipitem->setAttribute('id', "clipitem-" . ($index + 1));
            $track->appendChild($clipitem);
        }
        $clipitemPath = '//sequence/media/video/track[2]/clipitem[' . ($index + 1) .']';
        $xpath->query("$clipitemPath/in")->item(0)->nodeValue = $interval * $index;
        $xpath->query("$clipitemPath/out")->item(0)->nodeValue = $interval * ($index + 1);
        $xpath->query("$clipitemPath/start")->item(0)->nodeValue = $interval * $index;
        $xpath->query("$clipitemPath/end")->item(0)->nodeValue = $interval * ($index + 1);
        $xpath->query("$clipitemPath/filter[1]/effect/name")->item(0)->nodeValue = trim($caption);
        $xpath->query("$clipitemPath/filter[1]/effect/parameter[1]/value")->item(0)->nodeValue = base64_encode($first . mb_convert_encoding(sprintf($captionTemplate, $caption), 'UTF-16LE'));
    }
    $template->save($result->output);
        
} catch( Exception $e ) {
    echo $e->getMessage();
    $printer = new ConsoleOptionPrinter();
    echo $printer->render($specs);
    
}